import Header from "@/components/layout/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container p-2 md:p-4">
          <Header />
          <main>
          {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
